name: Generate and push doxygen's documentation

on:
  push:
    branches:
      - main
    paths:
      - 'Doxyfile'
      - 'include/**'
      - 'src/**'
      - 'docs/image/**'
      - 'docs/doxygendocs/**'

jobs:
  generate-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz git

      - name: Prepare directories
        run: |
          mkdir -p docs
          rm -rf docs/doxygen
          mkdir -p docs/doxygen

      - name: Make documentation
        run: doxygen Doxyfile

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit documentation
        run: |
          git add docs/doxygen
          git commit -m "Automated documentation update" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/doxygen
          commit_message: "Deploy documentation to GitHub Pages"
